### ISSUE TITLE
Telestrat joysticks does not work

### ISSUE THREAD

**Issue by jedeoric** [pete-gordon/oricutron#122]
I think that telestrat joysticks does work. If we select sdl1 input or keyboard input, via2 registers are not affected by anymove.

I am under windows, does someone see theses joysticks working ?

**Comment by assinie** [comment]
Does not work under Linux too.

The issue is in joy_buildmask() function in joystick.c
This function modify only the VIA1 registers regardless of the oric machine type
```C
  oric->porta_joy = mkmask;
  if( gimme_port_a )
  {
    oric->via.write_port_a( &oric->via, 0xff, mkmask );
    oric->porta_is_ay = SDL_FALSE;
  } else {
    if( !oric->porta_is_ay )
    {
      oric->via.write_port_a( &oric->via, 0xff, oric->porta_ay );
      oric->porta_is_ay = SDL_TRUE;
    }
  }
```
Also, the mkmask status is only set for PASE/ALTAI or IJK interfaces and the joysel variable is set from the VIA1 port A.

I think the joy_buildmask() function need to check the oric machine type against TELESTRAT

**Comment by jedeoric** [comment]
Does someone work on this issue, if not i can do it, i am installing my toolchain here.

**Comment by assinie** [comment]
You can take it
