### ISSUE TITLE
"Hell's Temple" compatibility issues (Oric-1/Atmos)

### ISSUE THREAD

**Issue by rzumer** [pete-gordon/oricutron#134]
I noticed text corruption when running in Oric-1 mode in the title "Hell's Temple". With the serial modem enabled, just bumping into the wall at the start repeatedly will cause that to happen. Eventually the player's status is completely unreadable and I wouldn't be surprised if it caused crashes, but I have not gotten far enough to check.
![image](https://user-images.githubusercontent.com/7488362/53055886-5d257800-3477-11e9-836f-605040dd267e.png)

It persists after being booted out by the game (following a game over).
![image](https://user-images.githubusercontent.com/7488362/53055973-a37ad700-3477-11e9-8313-203bd554b73d.png)

After disabling the serial modem the display is fine, but the same issue occurs regardless of that setting when loading from a save file. Sample save tape below: enter the name "EUCLIDE" and insert on load. Note that this sample was generated on Atmos rather than Oric-1 and it is the only one I have, so I have no idea if it is caused by the difference in models used to write and read the tape.
[euclide.zip](https://github.com/pete-gordon/oricutron/files/2882855/euclide.zip)

This title targets Oric-1, but when running on Atmos it seems to work correctly until trying to load from a save, which crashes to the debugger.

With Atmos (perhaps Oric-1 as well) I have heard secondhand that status text gets garbled under certain conditions as well, possibly involving combat. The same person who reported these issues to me also noted that after a certain amount of turns/time, the game crashes internally with a stack overflow (no crash to debugger as far as I know), and this has been reproduced on both models.

I have not yet compared these results with other emulators.

**Comment by assinie** [comment]
I tried with Euphoric in Oric-1mode and have the same result, so it's not an issue with Oricutron but a bug in the software (or the Oric-1 ROM).

**Comment by rzumer** [comment]
Thank you for checking. Have you considered the possibility of it being a shared bug between Euphoric and Oricutron?

**Comment by assinie** [comment]
I think the probability of a bug common to Euphoric and Oricutron is very low because these 2 emulators have np source files in common (as far as I know).

**Comment by assinie** [comment]
I looked at the program and it looks like it's for an Oric-1 and not for an Atmos because there are calls to ROM v1.0 routines for reading the backup file.
If started in Atmos mode, everything will work properly except reading the backup file (because of the calls to ROM v1.0 routines).

So I think it's something related to the initialization of the ROM v1.0 and the variables management.
When you start in Oric-1 mode, some memory pointers are "*incorrect*", HIMEM is set to $9F00.
If you do **HIMEM #9800** before the **CLOAD ""**, then you can ***WALK INTO A WALL*** without corrupting the character set :smiley: 
(#9800 is the default value in Atmos mode).

**Comment by rzumer** [comment]
Very nice, thanks for the information and the workaround.

**Comment by iss000** [comment]
closed.
